baseURL: "https://asarmakeeva.com"
languageCode: "en-us"
title: "Anastasiia Sarmakeeva"
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: https://asarmakeeva.github.io/
      weight: 1

    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
#this is upper part of the website
  title: Anastasiia Sarmakeeva
  #"Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "resources/_gen/images/icon.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Anastasiia."
    subtitle: "I am a graduate student at the George Washington University"
    content: "My interest lies in reproducible research, HPC and CFD"
    image: /images/Sarmakeeva.png
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://example.com
        - icon: fab fa-twitter
          url: https://twitter.com/asarmakeeva
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/Sarmakeeva.png"
    content: |-
            I am a graduate student at George Washington University, pursuing my Ph.D. in the field of Computational Fluid Dynamic with focus on reproducible research. I have a strong background in applied math and computer science, which have prepared me well for the challenges of my graduate research project. In my free time, I have a keen interest in quantitative finance, web3 technologies, and contemporary art. I am currently based in Washington, DC. 

            My research on simulating water flooding with solid body rotation and two-phase fluid. I am excited to see where my studies and interests will take me in the future.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Pyhon3"
        - "C++"
        - "Cloud Computing"
        - "OpenFoam"
        - "p5.js"
        - "CUDA"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Graduate Assistant"
        company: "The George Washington University"
        date: "May 2020 - current"
        featuredLink:
          enable: true
          name: "Assisting with the class Engineers Code"
          url: "https://github.com/engineersCode" 

        content: |
         - Created exams and maintain online learning platform
         - Consulted in python engineering students in topics regression, basic data analysis, numerical methods for solving system of equations
        

      - job: "Research Assistant"
        company: "The George Washington University"
        date: "May 2021 - May 2022"
        featuredLink:
          enable: true
          name: "Collaboration with FDA"
          url: "https://example.com"
        content: "It was a project to provide a medical device simulation examination running with open source and proprietary software."

      - job: "Computational Research Developer"
        company: "Department of Particulate Flow Modelling"
        date: "October 2018 - May 2019"
        #featuredLink:
        #  enable: true
        #  name: "Assisting with the class Engineers Code"
       #   url: "https://github.com/engineersCode" 
        content: |
         - Developed an approximation model for computational simulation with Volume of Fluid Method approach and Discrete Element Method
         - Presented computational model for solving Navier-Stokes equations for the Fluid Structure Interaction Problem

      - job: "Junior Researcher"
        company: "UB RAS"
        date: "November 2013 - September 2018"
        content: |
          - Provided research at Computational Simulation Research Laboratory
          - Created scalable algorithms for matrix inversion in HPC with CUDA library
          - Studied computer simulation of fluid flow and deformable bodies and structures
          - Simulation of interaction of fluid flows with solid deformable and movable bodies with meshfree and grid methods

    #  - job: "UI/UX Designer"
     #   company: "Netflix"
      #  companyUrl: "https://example.com"
      #  date: "June 2017 - Nov 2019"
      #  featuredLink:
      #    enable: true
      #    url: "https://example.com"
      #  content: |
      #    I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #    - Lead backend developer for a product.
      #    - Created a frontend design for a product.

    #  - job: "Product Designer"
    #    company: "Google"
     #   companyUrl: "https://example.com"
     #   date: "Feb 2016 - Mar 2017"
     #   content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    # index: true
    items:
      - title: "Doctor of Philosophy in Mechanical & Aerospace Engineering"
        school:
          name: "The George Washington University, School of Engineering & Applied Science"
          #url: "https://example.org"
        date: "2020 - current"
        GPA: "3.45 out of 4.0"
        content: |-
            - Specialty in Computational Fluid Dynamic. 
            - Project with FDA developing open source& reproducible workflow.
      - title: "Specialist Degree at Applied Math&Computer Science"
        school:
          name: "The Udmurt State University"
         # url: "https://example.org"
        date: "2009 - 2014"
        GPA: "4.5 out of 5.0"
        content: |-
          - Thesis: Parallel Algorithms For Sparse Matrix Inversion on GPU
        #featuredLink:
         # enable: true
         # name: "My academic record"
         # url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Fulbright Resercher from the US Department of State
        content: Worked for a year at Lorena Barba's lab.
  #      url: https://example.com
      - title: Ernst Mach Grant from Austrian Goverment
        content: Sponsored a year of researhc in Austria
      - title: Center of Mathematical Finances from the Higher School of Economics
        content: Learned and worked on projects in subjects -  Stock Analysis, Derivatives, Machine Learning, Probability and Stochastic Processes.
        url: "https://github.com/asarmakeeva/cmf-projects"
      - title: 3MT People's Choice Award
        content: Presented my thesis in 3 minute for general audience.
      - title: Quantitative Finance Women's PhD Mentorship Program
        #content: Contributed to a open source project.
        #url: https://example.com

  # projects
  #projects:
  #  enable: true
    # title: "Custom Name"
  #  items:
  #    - title: Hugo Profile
  #      content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
  #      image: /images/projects/profile.png
  #      featured:
  #        name: Demo
  #        link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
  #      links:
  #        - icon: fa fa-envelope
  #          url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
  #        - icon: fab fa-github
  #          url: https://github.com/gurusabarish/hugo-profile
  #        - icon: fab fa-twitter
  #          url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

  #    - title: Image Converter
  #      content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
  #      image: /images/projects/converter.jpg
  #      featured:
  #        name: Demo
  #        link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
  #      links:
  #        - icon: fab fa-github
  #          url: https://github.com/gurusabarish/converter

  #    - title: Hugo Profile V2
  #      content: A clean and simple Hugo template for personal portfolio and blog.
  #      image: /images/projects/profile2.jpg
  #      featured:
  #        name: Demo V2
  #        link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
  #      links:
  #        - icon: fab fa-github
  #          url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    #title: "Custom name"
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: asarmakeeva@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/asarmakeeva
      linkedin: https://www.linkedin.com/in/anastasiia-sarmakeeva-5a0134b2/
      twitter: https://twitter.com/asarmakeeva
      instagram: https://www.instagram.com/asarmakeeva/
